### ISSUE TITLE
Gman.ZipEngine - Zip file corrupted 

### ISSUE THREAD

**Issue by ghost** [maxmods/gman.mod#4]
Hello, sir gman. Can you please update this mod?
When my sister compresses files with 2.3 GB or higher.. her zip file is corrupted when she's opening it with WinRAR or other compressing Apps.
Please fix this how to compress higher files. Thank you very much.

**Comment by woollybah** [comment]
The module appears to use a very old version of the zip library, which doesn't support large files.
There are no current plans to update the library.

**Comment by woollybah** [comment]
This is what I got, using a similarly named file... There's no extra folder, just the file stored in the zip.
When I extract it, it extracts the filename correctly.
[MyFavMusic.zip](https://github.com/maxmods/gman.mod/files/7872160/MyFavMusic.zip)

**Comment by woollybah** [comment]
I recommend you look at https://github.com/bmx-ng/archive.mod instead.
