### ISSUE TITLE
Addfile() Function - Error

### ISSUE THREAD

**Issue by WGZero05** [maxmods/gman.mod#5]
Hello mr.gman. I'm new to blitzmax NG and i've been using it for a month. 
I tried to use this Mod for NG but i got errors and glitch when i'm using Addfile() function.
I zipped some of my videos with different language names but some of them didn't compress properly especially their proper names.
And not only that... It made a new folder inside of my zip file even though i didn't even add folder for my zip file.
Probably some of the names of my videos have strange characters like Chinese or Korean characters. Why your mod can not do compress files with strange names? 

For example: I downloaded a video from youtube and the title of that video is chinese or the title has strange characters..
e.g: "샤이니_Sherlock•셜록 Music Video.mp4" ( this is just an example )

Example:
zw.openzip ("MyFavVideo.zip")
zw.addfile ("nameswithdifferentcharacters.mp4")
zw.closezip()

Please fix this issue that AddFile() function can also compress the files with their original names. Thank you.

**Comment by WGZero05** [comment]
Thank you for the update, woollybah. Sadly i'm getting this error..

![image](https://user-images.githubusercontent.com/97401547/148976942-9576f463-01eb-4854-a79b-1da8a9403f1b.png)

**Comment by WGZero05** [comment]
Hello Sir Brucey. This is the issue I was talking about.
When I'm compressing this file, Addfile function was creating a folder and the name is not the same too.
Can you fix this issue? please.

zw.openzip ("MyFavMusic.zip")
zw.addfile ("SHINee 샤이니_Sherlock•셜록 (Clue   Note)_Music Video.mp3")
zw.closezip()


You can download the file here and try it :)
https://www.mediafire.com/file/6znkpxdp8y8ry20/SHINee_%25EC%2583%25A4%25EC%259D%25B4%25EB%258B%2588_Sherlock%25E2%2580%25A2%25EC%2585%259C%25EB%25A1%259D_%2528Clue_Note%2529_Music_Video.mp3/file

**Comment by WGZero05** [comment]
Please reply. I am waiting patiently. 🙏

**Comment by woollybah** [comment]
This is what I got, using a similarly named file... There's no extra folder, just the file stored in the zip.
When I extract it, it extracts the filename correctly.
[MyFavMusic.zip](https://github.com/maxmods/gman.mod/files/7872160/MyFavMusic.zip)

**Comment by WGZero05** [comment]
The name is not the same anymore inside the zip you gave me. The Korean letters are missing. :(
Please download and use the original .mp3 file i gave u in the link and see it for yourself. This is the result I got.
![image](https://user-images.githubusercontent.com/97401547/149613137-3d0c69c9-f6f3-4d87-96b5-26d5c9588ff7.png)

[MyFavMusic.zip](https://github.com/maxmods/gman.mod/files/7874447/MyFavMusic.zip)
.

**Comment by WGZero05** [comment]
And also about my 2nd question has not been answered and solved yet.
When i'm going to uncheck the debug build and quick scan and compile it.. NG always giving me this error.

![image](https://user-images.githubusercontent.com/97401547/149613248-5d2ed1d6-7bb5-4e19-831e-4967b6cac8a4.png)

**Comment by WGZero05** [comment]
HELLO!? 
I'm losing hope using this crap blitzmax compiler. Is this still can be fixed or not?

**Comment by woollybah** [comment]
You will need the latest brl.mod to fix the build error. Some changes were made to better support UTF8 streams.

You are right. When I opened it on macOS, it showed the filename correctly, but not on Windows.
It's quite possible that the version of zip used by zip-engine isn't so unicode friendly as it needs to be. It is a very old version of the library.

**Comment by woollybah** [comment]
How does this one look ?
[MyData.zip](https://github.com/maxmods/gman.mod/files/7898209/MyData.zip)

**Comment by woollybah** [comment]
Doesn't appear to work properly either :)

It seems that unicode and zip are complicated subjects.
The zip format did not properly support unicode until 6.3.0, which this library may predate...

**Comment by woollybah** [comment]
Hmm. How about this one..
[MyData.zip](https://github.com/maxmods/gman.mod/files/7899681/MyData.zip)

**Comment by WGZero05** [comment]
OH! THANK GOD! for the reply.
How did you do it? The gman.zipengine is now ok to compress files with any names?
and Where can I download the latest brl.mod?

**Comment by woollybah** [comment]
The zip was *not* built with gman.zipengine. The version of "zip" it is built with does not support correct use of unicode filenames, so it turns out that my recent changes to improve support for that don't work correctly.

The zip was built using a different module that I've been working on, but it's not quite ready for release yet. It uses `libarchive` to support multiple archive formats, but even with this library, getting unicode names working is proving to be difficult. But I appear to have resolved most of the issues, and as you can see from the zip, it created a file with correct file names.

**Comment by WGZero05** [comment]
Wow! I'm so happy to hear THAT! REally!
You are making a new Mod.  🙏 I'm so excited to use it! I can't WAITTT!!!. Thanks a lot!  🙏

**Comment by woollybah** [comment]
The new module is available from here : https://github.com/bmx-ng/archive.mod
The latest brl.mod is available from here : https://github.com/bmx-ng/brl.mod

There's an example of usage in the examples folder in `archive.mod/zip.mod/examples`
There will be more archive options arriving soon - like zstd, 7zip, etc.

**Comment by WGZero05** [comment]
THANK YOU VERY VERY MUCH!!!
I got the strength again to do programming with Blitzmax. Much Appreciated!  🙏🙏🙏🙏🙏🙏
You're the man, Sir Brucey! <3

**Comment by WGZero05** [comment]
I'll keep in touch to check the new updates for the Mod. 🙏

**Comment by WGZero05** [comment]
I love the mod so much and so easy to use.
But I'm getting this error and I don't know what the cause is.
And I hope you will add more new futures to this amazing Mod. 🤗 And also lots of examples like 'How to add a folder inside my zip file'.
I have no idea how to add a folder inside the zip. hehehe

![image](https://user-images.githubusercontent.com/97401547/151153819-b5b13e63-0873-4a92-99db-5a81d0716915.png)

**Comment by woollybah** [comment]
The empty names may be unicode characters unable to be printed in the output there.
I noticed this on Windows when I was testing - The strings themselves contained valid text, and they rendered as expected on both macOS and Linux.

Do you want an empty folder, or files within a folder?
For files, I believe you can just prefix the second parameter, `pathname`, with the path, and the folders will be created automatically.
So, for example -
```blitzmax
wa.AddEntry("myfile.txt", "path/in/archive/to/file/myfile.txt")
```

**Comment by woollybah** [comment]
Updated the module with some fixes and additions. Check out the zip example for details.

**Comment by woollybah** [comment]
I'll close this now. If you have any issues with the other mod, feel free to open a new issue there.

**Comment by WGZero05** [comment]
It works and also I can change the name too with the same data inside. Thank you very much.
wa.AddEntry("testdata.txt", "testfolder/Data.txt")

But i don't know how to add a password to my zip file. Hehehe

**Comment by WGZero05** [comment]
And btw since I downloaded and patched the brl.mod from the link you gave me to my BlitzMax NG, I'm always getting this error "Import Image.PNG".
I don't have this Image.PNG and I don't know how to download it. And everything was so messed up!. I can't even use the LoadIconStrip Function and more.
The codes that i've been working on for 2 weeks were messed up. So i deleted the whole BlitzMax folder and extract the stable BlitzMax NG again on my hard drive.


Well If you don't mind, can you Archive your own stable version? So that I am not having a hard time downloading mods everywhere.
What I meant is can you separate your own version so that I can focus on your own BlitzMaxNG with your new Mods?

For example: 
https://blitzmax.org/downloads/
BlitzMax_win32_0.129.3.45.7z.  (This Archive Blitzmax NG is a stable release with its mods and everything.)


Another Example:
BlitzMax_win32_BruceyStableRelease_1-27-2022.7z. (and This BlitzMax NG is your stable release with your new Mods and updates.)


You know like that. Can you please separate your own BlitzMax NG and Archive-it, so that I can download it and use it separately on my Computer with no worries? 🙏


Btw I am using BlitzMax NG Win32 x86/x64 build.
https://github.com/bmx-ng/bmx-ng/releases/download/v0.129.3.45.win32/BlitzMax_win32_0.129.3.45.7z
